icao_code = "KORD"
name = "Chicago O'Hare Intl"
lat = 41.977000
lon = -87.908167

[runways]

[runways.10C]
threshold_lat_a = 41.965963
threshold_lon_a = -87.931514
threshold_lat_b = 41.965442
threshold_lon_b = -87.931510

# [runways.27L]


# [runways.27C]


# [runways.27R]


# [runways.28L]


[runways.28C]
threshold_lat_a = 41.9660380
threshold_lon_a = -87.891846
threshold_lat_b = 41.965513
threshold_lon_b = -87.891842

# [runways.28R]
